In [1]:
import re
import string
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

In [2]:
with open("textbook_as_text.txt", "r", encoding='utf-8') as file:
    text = file.read()

In [3]:
def print_n_lines_from_m(text, n, m):
    print(text[m:(n+m)])

In [4]:
print_n_lines_from_m(text, 10000, 1000000)

overall learning experience. Cengage Learning reserves the right to remove additional content at any time if subsequent rights restrictions require it.
Copyright 2019 Cengage Learning. All Rights Reserved. May not be copied, scanned, or duplicated, in whole or in part.  WCN 02-200-203
www.EBooksWorld.ir

Chapter 7    Introduction to Structured Query Language (SQL)   287
Now, consider the same query but with one additional attribute added to the SELECT
column list:
SELECT
V_CODE, V_NAME, P_QOH, COUNT(P_CODE), AVG(P_PRICE)
FROM

PRODUCT JOIN VENDOR ON PRODUCT.V_CODE =
VENDOR.V_CODE
GROUP BY	 V_CODE, V_NAME
ORDER BY	 V_NAME;
This query will not execute but generates a “not a GROUP BY expression” error.
The FROM clause operates exactly the same as in the previous query to join the
PRODUCT and VENDOR tables. The GROUP BY clause operates exactly the same as
in the previous query to form collections of the rows based on vendor code and vendor
name. The SELECT column list projects the product quantity on hand in addition to
the vendor code, vendor name, product code, and product price. The error occurs when
the aggregate functions attempt to reduce each collection to a single row. The aggregates
can reduce price by taking an average, reduce product code by counting, display vendor
code and vendor name because all rows in the collection have the same value, but what
about the quantity on hand attribute? Each row in a collection may have different values
for the quantity on hand for the products in that collection. The query does not group by
P_QOH, so the DBMS cannot know with certainty that the rows all have the same value.
The query does not apply an aggregate function to the P_QOH attribute, so the DBMS
does not know how to calculate a single value to represent P_QOH in the collection.
Therefore, an error is generated. To fix this error, either an aggregate function must be
applied to P_QOH so that a single value can be calculated, or P_QOH must be added to
the GROUP BY clause so that the DBMS can enforce that every row in the group has the
same value for that attribute. Notice the difference in the results of these two possible
solutions.
SELECT

V_CODE, V_NAME, SUM(P_QOH) AS TOTALQTY,
COUNT(P_CODE) AS NUMPRODS, AVG(P_PRICE) AS AVGPRICE
FROM

PRODUCT JOIN VENDOR ON PRODUCT.V_CODE =
VENDOR.V_CODE
GROUP BY	 V_CODE, V_NAME
ORDER BY	 V_NAME;
Figure 7.43 shows the result with a SUM function being applied to P_QOH. The
result has six rows.
FIGURE 7.43  GROUPING BY VENDOR CODE AND VENDOR NAME
27900_ch07_ptg01_243-358.indd   287
31/10/17   5:39 PM
Copyright 2019 Cengage Learning. All Rights Reserved. May not be copied, scanned, or duplicated, in whole or in part. Due to electronic rights, some third party content may be suppressed from the eBook and/or eChapter(s).
Editorial review has deemed that any suppressed content does not materially affect the overall learning experience. Cengage Learning reserves the right to remove additional content at any time if subsequent rights restrictions require it.
Copyright 2019 Cengage Learning. All Rights Reserved. May not be copied, scanned, or duplicated, in whole or in part.  WCN 02-200-203
www.EBooksWorld.ir
288   Part 3    Advanced Design and Implementation
SELECT

V_CODE, V_NAME, P_QOH, COUNT(P_CODE) AS NUMPRODS,
AVG(P_PRICE) AS AVGPRICE
FROM

PRODUCT JOIN VENDOR ON PRODUCT.V_CODE =
VENDOR.V_CODE
GROUP BY
V_CODE, V_NAME, P_QOH
ORDER BY
V_NAME;
Figure 7.44 shows the result when P_QOH is added to the GROUP BY clause. The
result has 14 rows and the values of the COUNT and AVG functions have changed since
the collections formed by the GROUP BY clause no longer contain the same sets of
rows. The number of groups changed because when the rows were grouped by vendor
code and vendor name (as in Figure 7.43), there was variation among the rows for the
values in P_QOH. In Figure 7.44, collections were formed by requiring all of the rows in
a group to have the same value for V_CODE, V_NAME, and P_QOH.
FIGURE 7.44  GROUPS CHANGED BY INCLUSION OF P_QOH
Including additional attributes in the GROUP BY clause does not always cause the
number of groups formed to change. For example, instead of adding P_QOH to the
query from Figure 7.42, consider the addition of V_STATE instead. In this case, adding
V_STATE to the GROUP BY clause does not change the values for the count of prod-
ucts or the average price because every collection formed from grouping on V_CODE
and V_NAME had only one value for V_STATE within that collection, as shown in
Figure 7.45.
As you can see, great care must be taken when constructing queries that use groups
and aggregate functions because the addition of even one attribute can significantly
change the results returned by the query.
7-7c  HAVING Clause
Aggregate functions are very powerful and are used frequently in reporting. Most often,
aggregate functions appear in the SELECT column list of a query. It is also possible to
27900_ch07_ptg01_243-358.indd   288
31/10/17   5:39 PM
Copyright 2019 Cengage Learning. All Rights Reserved. May not be copied, scanned, or duplicated, in whole or in part. Due to electronic rights, some third party content may be suppressed from the eBook and/or eChapter(s).
Editorial review has deemed that any suppressed content does not materially affect the overall learning experience. Cengage Learning reserves the right to remove additional content at any time if subsequent rights restrictions require it.
Copyright 2019 Cengage Learning. All Rights Reserved. May not be copied, scanned, or duplicated, in whole or in part.  WCN 02-200-203
www.EBooksWorld.ir

Chapter 7    Introduction to Structured Query Language (SQL)   289
use aggregate functions in the ORDER BY clause to sort results based on a calculated
aggregate value. However, restricting data based on an aggregate value is slightly more
complicated and can require the use of a HAVING clause. The syntax for a HAVING
clause is:
SELECT
columnlist
FROM
tablelist
[WHERE
conditionlist ]
[GROUP BY
columnlist ]
[HAVING
conditionlist ]
[ORDER BY
columnlist [ASC | DESC] ];
The HAVING clause operates very much like the WHERE clause in the SELECT state-
ment. However, the WHERE clause applies to columns and expressions for individual
rows, whereas the HAVING clause is applied to the output of a GROUP BY operation.
For example, suppose that you want to generate a listing of the number of products in
the inventory supplied by each vendor. However, this time you want to limit the listing
to products whose prices average less than $10. The query requires both a GROUP BY
clause and a HAVING clause, as illustrated in in Figure 7.46.
SELECT
V_CODE, COUNT(P_CODE) AS NUMPRODS
FROM
PRODUCT
GROUP BY
V_CODE
HAVING
AVG(P_PRICE) < 10
ORDER BY
V_CODE;
FIGURE 7.45  GROUPS INCLUDING V_STATE
FIGURE 7.46  APPLICATION OF THE HAVING CLAUSE
HAVING
A clause applied to the
output of a GROUP BY
operation to restrict
selected rows.
If you use the WHERE clause instead of the HAVING clause, the query in ­
Figure 7.46
will produce an error message. That is not to say that a query cannot contain both a
WHERE clause and a HAVING clause, just that the clauses do different things. WHERE
27900_ch07_ptg01_243-358.indd   289
31/10/17   5:39 PM
Copyright 2019 Cengage Learning. All Rights Reserved. May not be copied, scanned, or duplicated, in whole or in part. Due to electronic rights, some third party content may be suppressed from the eBook and/or eChapter(s).
Editorial review has deemed that any suppressed content does not materially affect the overall learning experience. Cengage Learning reserves the right to remove additional content at any time if subsequent rights restrictions require it.
Copyright 2019 Cengage Learning. All Rights Reserved. May not be copied, scanned, or duplicated, in whole or in part.  WCN 02-200-203
www.EBooksWorld.ir
290   Part 3    Advanced Design and Implementation
is used to restrict rows and is executed prior to the GROUP BY clause. Because WHERE
executes before GROUP BY, WHERE cannot contain an aggregate function because the
collections needed by the aggregate function do not exist yet. The HAVING clause is
used to restrict groups and is executed after the GROUP BY clause. HAVING can con-
tain aggregate functions because the collections are formed by the GROUP BY clause
before the HAVING is executed. HAVING restricts groups. It is not possible for a HAV-
ING clause to restrict some rows in a group but leave others. HAVING either keeps or
eliminates the entire group, so the condition in the HAVING clause must be applicable
to the entire group. For this reason, HAVING clauses not only are allowed to contain
aggregate functions, but they almost always do.
You can combine multiple clauses and aggregate functions. For example, consider the
following SQL statement:
SELECT
V_CODE, V_NAME, SUM(P_QOH * P_PRICE) AS TOTCOST
FROM

PRODUCT JOIN VENDOR ON PRODUCT.V_CODE =
VENDOR.V_CODE
WHERE
P_DISCOUNT > 0
GROUP BY
V_CODE, V_NAME
HAVING
(SUM(P_QOH * P_PRICE) > 500)
ORDER BY
SUM(P_QOH * P_PRICE) DESC;
This statement does the following:
• Joins the product and vendor tables using V_CODE as the common attribute
• Restricts to only the rows with a discount greater than 0
• Groups the remaining rows into collections based on V_CODE and V_NAME
• Aggregates the total cost of products in each group
• Restricts to only the groups with totals that exceed $500
• Lists the results in descending order by the total cost
Note the syntax used in the HAVING and ORDER BY clauses; in both cases, you
should specify the column expression (formula) used in the SELECT statement’s col-
umn list, rather than the column alias (TOTCOST). Some RDBMSs allow you to replace
the column expression with the column alias, while others do not.
7-8  Subqueries
The use of joins in a relational database allows you to get information from two or more
tables

To do:
- Remove page numbers
- Remove copy right information
- Remove website links

In [5]:
from collections import Counter

# Go through each line in the text and count the number of times each LINE appears
counter = Counter(text.split("\n"))

counter.most_common(10)

[('Copyright 2019 Cengage Learning. All Rights Reserved. May not be copied, scanned, or duplicated, in whole or in part. Due to electronic rights, some third party content may be suppressed from the eBook and/or eChapter(s).',
  833),
 ('Editorial review has deemed that any suppressed content does not materially affect the overall learning experience. Cengage Learning reserves the right to remove additional content at any time if subsequent rights restrictions require it.',
  833),
 ('Copyright 2019 Cengage Learning. All Rights Reserved. May not be copied, scanned, or duplicated, in whole or in part.  WCN 02-200-203',
  833),
 ('www.EBooksWorld.ir', 833),
 (' ', 562),
 ('\t', 561),
 ('\xad', 375),
 ('e', 204),
 ('SELECT\t', 187),
 ('r', 165)]

In [6]:
# Get the most common lines from the counters
most_common_lines = [line for line, _ in counter.most_common(8)]

# Split the text into lines
lines = text.split("\n")

# Remove the lines that match the most common lines
filtered_lines = [line for line in lines if line not in most_common_lines]

# Join the filtered lines back into a single text
filtered_text = "\n".join(filtered_lines)

# save new text to file
with open("filtered_text.txt", "w", encoding='utf-8') as file:
    file.write(filtered_text)

In [7]:
# Go through each line in the text and count the number of times each LINE appears
counter = Counter(filtered_text.split("\n"))

counter.most_common(20)

[('SELECT\t', 187),
 ('r', 165),
 ('FROM\t', 159),
 ('o', 157),
 ('Note', 156),
 ('✓\t', 156),
 ('t', 143),
 ('a', 131),
 ('n', 124),
 ('i', 119),
 ('31/10/17   5:39 PM', 114),
 ('1', 105),
 ('s', 91),
 ('06/11/17   9:39 AM', 80),
 ('WHERE\t', 76),
 ('2', 72),
 ('c', 68),
 ('PRODUCT', 68),
 ('31/10/17   6:58 PM', 68),
 ('31/10/17   5:35 PM', 66)]

In [8]:
import re

# Define the pattern for dates like so: 31/10/17   5:39 PM
date_pattern = r"\b\d{2}/\d{2}/\d{2}\s+\d{1,2}:\d{2}\s(?:AM|PM)\b"

for line in filtered_text.split("\n"):
    if re.search(date_pattern, line):
        # Remove lines that contain the date pattern
        filtered_text = filtered_text.replace(line, "")

# Remove any empty lines
filtered_text = "\n".join([line for line in filtered_text.split("\n") if line])

lines_to_remove = ['www.cengagebrain.com. ', 'www.cengagebrain.com.']

filtered_text = "\n".join([line for line in filtered_text.split("\n") if line not in lines_to_remove])

# Go through each line in the text and count the number of times each LINE appears
counter = Counter(filtered_text.split("\n"))

counter.most_common(20)

[('SELECT\t', 187),
 ('r', 165),
 ('FROM\t', 159),
 ('o', 157),
 ('Note', 156),
 ('✓\t', 156),
 ('t', 143),
 ('a', 131),
 ('n', 124),
 ('i', 119),
 ('1', 105),
 ('s', 91),
 ('WHERE\t', 76),
 ('2', 72),
 ('c', 68),
 ('PRODUCT', 68),
 ('d', 61),
 ('\x07', 60),
 ('–', 54),
 ('✓', 53)]

In [9]:
# save new text to file
with open("textbook_as_text.txt", "w", encoding='utf-8') as file:
    file.write(filtered_text)